start-redpanda:
	@echo "Starting Redpanda..."
	docker compose -f redpanda.yml up -d

stop-redpanda:
	@echo "Stopping Redpanda..."
	docker compose -f redpanda.yml down

start-feature-pipeline:
	@echo "Starting Feature Pipeline..."
	docker compose -f feature-pipeline.yml up -d

stop-feature-pipeline:
	@echo "Stopping Feature Pipeline..."
	docker compose -f feature-pipeline.yml down